stages:
  preprocessing:
    cmd: python preprocessing.py data/titanic.csv
    deps:
    - data/titanic.csv
    - preprocessing.py
    outs:
    - data/prepared
    params:
    - preprocessing.seed
    - preprocessing.split
  featurize:
    cmd: python features.py data/prepared data/features
    deps:
    - data/prepared
    - features.py
    params:
    - featurize.seed
